language: node_js
node_js:
  - 6.14.3
  - 8.11.3
  - 10.5.0
deploy:
  - provider: script
    script: ./node_modules/.bin/nlm release
    skip_cleanup: true
    'on':
      branch: master
      node: 10.5.0
