#!/usr/bin/env bash
set -e
git init
git config user.name "nlm"
git config user.email "nlm@example.com"

bash $(dirname $0)/fix-commit

echo "console.log('other stuff');" > index.js
echo "console.log('untracked file');" > untracked.js
git add index.js
