#!/usr/bin/env bash
set -e
echo '{
  "name": "nlm-test-pkg",
  "version": "99.6.2",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.example.com/some-org/nlm-test-pkg"
  },
  "publishConfig": {
    "registry": "http://127.0.0.1:3000"
  }
}' >package.json
